// TODO ACTIONS
export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const UPDATE_TODO_STATUS = 'UPDATE_TODO_STATUS';
// USER ACTIONS
export const GET_USER_LIST = 'GET_USER_LIST';
export const REMOVE_USER_ITEM = 'REMOVE_USER_ITEM';
